### ISSUE TITLE
0.1 fragen

### ISSUE THREAD

**Issue by dietsch66** [simonpucher/AgenaTrader#20]
Meine Punkte die mir ad hoc einfallen:

Man sollte die Vorgehensweise strukturieren um einen schnellen Erfolg zu haben.
Hier nur lose aufgeschrieben. sollte geordnet und besprochen werden.

Installation
global utilities - wo gehört die hinein? ich schmeiss sie in den indicators ordner bei mir
einbindung wie beschrieben hab ich noch nicht gemacht - erlärung warum man das tun sollte
step by step beschreibung wie man beginnen sollte

Verständnis
indicator-condition-strategie
backtest
offline arbeiten mit tickfiles?
ihr habt da eine statistik eingebaut. wie kann man die nutzen?

Test
debug

Dokumentation
word oder video? youtube, beschreibung im git. 
gibts eine möglichkeit die änderungen zu markieren.
wenn ihr täglich was ändert schau ich manchmal was anders ist?
mehr kommentare im code? da könnt ich vielleicht mal anhand eines indikators was versuchen?
vielleicht api dokumentation? 
ein programmierbeispiel durchziehen? denke riesiger aufwand für lau, dh ihr habt nix davon
weil ihr es eh schon könnt

sonstige fragen
könnt ihr auch andere broker anbinden? brauch ich tradeescort dazu?
kurse gratis bekommen?

das problem ist, das viele im internet alles gratis haben wollen.
und dann meckern

das wars für den anfang
als nächstes schreib ich dann mal die fragen zu den indikatoren auf.
aber das sollte man vielleicht erst später mal machen

**Comment by simonpucher** [comment]
Dieter danke für deinen input!
Wir werden die Punkte einfach Stück für Stück abarbeiten...

Zum Thema Verständnis habe ich ein kleines Tutorial inkl. Template Files erstellt:
https://github.com/simonpucher/AgenaTrader/issues/22

**Comment by simonpucher** [comment]
Einen Broker anbinden kann eigentlich nur Tradeescort selbst.
Selbiges gilt auch für die Kursstellung von Instrumenten. AT bietet den yahoo Datenfeed an, der ist zwar gratis aber beinhaltet auch keine Korrektur bei Aktiensplits oder ähnlichem! Das schaut dann so aus ;)
![apple_yahoo](https://cloud.githubusercontent.com/assets/3034492/15453918/16df2e38-2028-11e6-871e-815e1785f8d4.png)

**Comment by simonpucher** [comment]
In Bezug auf "ein programmierbeispiel durchziehen"
Wir haben ein offizielles AgenaTrader Repository erstellt wo die Vorgehensweise für das Erstellen von Scripts gut ersichtlich ist: https://agenatrader.github.io/Tutorials/site/index.html

**Comment by simonpucher** [comment]
@dietsch66 ist hier noch etwas offen?

**Comment by dietsch66** [comment]
Ah jetzt versteh ich

Aber das gibt’s ja schon

Irgendeine funktion im AT

 

Von: Simon Pucher [mailto:notifications@github.com] 
Gesendet: Samstag, 12. November 2016 13:45
An: simonpucher/AgenaTrader
Cc: dieter; Mention
Betreff: Re: [simonpucher/AgenaTrader] 0.1 fragen (#20)

 

@dietsch66 <https://github.com/dietsch66>  ist hier noch etwas offen?
