### ISSUE TITLE
verbesserungsvorschlag

### ISSUE THREAD

**Issue by dietsch66** [simonpucher/AgenaTrader#21]
hi,
gut wäre es wenn ihr bei eurem code folgendes einbaut

[Category("Test")]

dann das test durch simon oder sonstwas ersetzen.
dadurch hast du eine neue category bei der auswahl, was die sache erleichtert.

lg
dieter

**Comment by simonpucher** [comment]
Hi Dieter, das category Tag sollte eigentlich bereits bei allen Input Properties gesetzt sein. Falls es konkret wo fehlt bitte kurze Mitteilung wo dann setzen wir es dort.

**Comment by dietsch66** [comment]
Also beim mean … sehe ich es nicht

 

Von: Simon Pucher [mailto:notifications@github.com] 
Gesendet: Sonntag, 22. Mai 2016 12:23
An: simonpucher/AgenaTrader
Cc: dietsch66; Author
Betreff: Re: [simonpucher/AgenaTrader] verbesserungsvorschlag (#21)

 

Hi Dieter, das category Tag sollte eigentlich bereits bei allen Input Properties gesetzt sein. Falls es konkret wo fehlt bitte kurze Mitteilung wo dann setzen wir es dort.

**Comment by simonpucher** [comment]
In allen Files zu mean-reversal haben wir [Category("Parameters")] verwendet für alle Input Variablen zur Parametrisierung. Zusätzlich nutzen wir  [Category("Safety first!")] für Sicherheitseinstellungen bei Strategien. Vielleicht hast du noch eine alte Version? Dann einfach mal GitHub sychronisieren.

**Comment by dietsch66** [comment]
Hast du zeit für skypen heute?

Ich möchte dir das kurz erklären und vielleicht zeigen

 

 

Von: Simon Pucher [mailto:notifications@github.com] 
Gesendet: Sonntag, 22. Mai 2016 12:47
An: simonpucher/AgenaTrader
Cc: dietsch66; Author
Betreff: Re: [simonpucher/AgenaTrader] verbesserungsvorschlag (#21)

 

In allen Files zu mean-reversal haben wir [Category("Parameters")] verwendet für alle Input Variablen zur Parametrisierung. Zusätzlich nutzen wir [Category("Safety first!")] für Sicherheitseinstellungen bei Strategien. Vielleicht hast du noch eine alte Version? Dann einfach mal GitHub sychronisieren.

**Comment by simonpucher** [comment]
Klar einfach melden.

**Comment by simonpucher** [comment]
Hi Dieter, danke für den Hinweis via Skype und die Teamviewer Session!
Das Category Tag auf den Klassen ist sehr nützlich. Gilt zwar erst ab AT 1.9 aber wir können die Skripte ja schon mal in diese Richtung vorbereiten.

**Comment by dietsch66** [comment]
ich sehe es auch bei 1.8


Von meinem Samsung Galaxy Smartphone gesendet.-------- Ursprüngliche Nachricht --------Von: Simon Pucher <notifications@github.com> Datum: 24.05.2016  08:58  (GMT+01:00) An: simonpucher/AgenaTrader <AgenaTrader@noreply.github.com> Cc: dietsch66 <d.marschall@t-online.de>, Author <author@noreply.github.com> Betreff: Re: [simonpucher/AgenaTrader] verbesserungsvorschlag (#21) 
Hi Dieter, danke für den Hinweis via Skype und die Teamviewer Session!

Das Category Tag auf den Klassen ist sehr nützlich. Gilt zwar erst ab AT 1.9 aber wir können die Skripte ja schon mal in diese Richtung vorbereiten.

**Comment by simonpucher** [comment]
AH! Okay in der Indikator Auswahlliste taucht es nun auf, ich dachte das gilt auch in der Auswahlliste wenn man über das Menu rein geht und den Indikator im Visul Studio aufmacht! Super danke alles klar.
