### ISSUE TITLE
github auto anbindung

### ISSUE THREAD

**Issue by dietsch66** [simonpucher/AgenaTrader#23]
guten morgen,
an sich ist die idee nicht schlecht.
aber wie jetzt gerade bei der open range habe ich ein problem.
anscheinend funktioniert der indikator nicht.
der vorherige aber schon. nur wurde der jetzt automatisch überschrieben.
wie kann man das lösen?
indem ich nur fertige synce?
und die anderen in ein work directory?

ich habe auch visual studio2013 installiert und halbwegs hingebracht.
nur das mit dem debuggen startet nicht.
könn ma das vielleicht in einem teamviewer mit aufzeichnung lösen?

lg
dieter

**Comment by ckovar82** [comment]
hallo dieter!
du kannst im indikator https://github.com/simonpucher/AgenaTrader/blob/master/Indicator/Open_Range_Breakout_Indicator.cs dir jeweils die history anschauen und dann gezielt eine version manuell runterziehen. das sollte als erste schnelle hilfe mal zweckdienlich sein.

![image](https://cloud.githubusercontent.com/assets/18376618/15532636/18d85418-2261-11e6-8e55-2d88f097bb09.png)

**Comment by dietsch66** [comment]
danke

**Comment by dietsch66** [comment]
da oben gibts einen punkt wiki.
macht der sinn oder ist das wieder was zum einarbeiten und sehr aufwändig?

**Comment by ckovar82** [comment]
so wie ich das sehe, ist das wiki eine optionales github feature um das projekt näher zu beschreiben und zusätzliche informationen zu bieten.

bei unserem agenatrader projekt ist das wiki leer. aktuell haben wir auch nicht geplant, dort was reinzuschreiben :)

**Comment by dietsch66** [comment]
hm. vielleicht habe ich hier zu wenig programmierverständnis.
aber wenn ich jetzt einen indikator history mässig zurückgehe, dann müsste ich ja theoretisch auch das global file zurücknehmen, weil vielleicht die methoden fehlen.

hilft da eine versionsverwaltung?
oder ist das zu aufwändig?

macht eine trennung zwischen final und in progress sinn?
zb. ein work verzeichnis und darin die einzelnen files mit namenskonventionen?
zb. i_cop... c_cop... und s_copp für indikator,cond und strategy?

irgendwie bin ich ja froh, das ich noch nicht programmiere, aber wenn dann 3 damit arbeiten würden?

nur so mal meine gedanken

**Comment by simonpucher** [comment]
GitHub selbst ist an sich eh eine Versionsverwaltung. Du vermutest aber richtig es könnte sein, dass du dann auch den GlobalUtility Helper in einer alten Version laden müsstest. Der aktuelle sollte aber in den meisten Fällen auch funktionieren da wir fast nichts geändert haben sondern immer nur Funktion hinzugefügt haben.

Das die ORB nicht funktioniert irritiert mich da sie bei mir funktioniert (siehe Screenshot anbei) und ich in sync bin mit dem GitHub Projekt bin. Wir versuchen immer einen vollständigen Stand der auch im gesamten kompilierbar ist zur Verfügung zu stellen. 

![bildschirmfoto 2016-05-25 um 15 03 11](https://cloud.githubusercontent.com/assets/3034492/15540892/08311590-228a-11e6-9981-92ab51dc6dae.png)

Kann es sein dass du den ORB auf CFD Basis in Verwendung hast? Dort werden dann die Marktdaten ausgelesen und die werden 0 Uhr sein da Standardmäßig bei CFD 0h in den Marktdaten steht. Könnte das sein?

**Comment by dietsch66** [comment]
das könnte sein. weisst ja eh - XTB
reimt sich sogar :-)

**Comment by simonpucher** [comment]
Auf XTB funktionieren derzeit nur der DOW und der DAX. Das ist hardcodiert. Beim AT sind CFD Märkte auf 0h gesetzt daher weis die ORB nicht wann die Handelszeiten sind. Klick mal auf DE.30.XTB und US.30.XTB. Dort sollte die ORB gezeichnet werden. Falls du für andere CFD die Zeiten weißt können wir das ja erstmal sammeln und codieren das beim nächsten update rein.

**Comment by dietsch66** [comment]
hm.
ich glaube ja, das es für cfds generell keine kurse zwischen 8 und 9 gibt.
vorschlag:
was wäre, wenn man generell anstelle 0 für alle die nicht eingetragen sind dummymässig von 9 bis 10 nimmt?
oder man es mittels parameter einstellen kann?

**Comment by simonpucher** [comment]
Genau ja, du kannst bereits jetzt für den DAX CFD und für den DOW CFD als Parameter die Uhrzeit einstellen. Andere Märkte müsste man noch statisch hinzufügen.

**Comment by dietsch66** [comment]
habs in den globals gefunden. 
jetzt könnt ich mich damit rumspielen und dort sachen eintragen.
kann ich aus den stammdaten eines cfds die börse rausfinden.
zb für deutsche steht irgendwo de?
oder sehe ich auch die art des wertpapiers? index, cfd, ....

**Comment by simonpucher** [comment]
![bildschirmfoto 2016-05-25 um 15 45 43](https://cloud.githubusercontent.com/assets/3034492/15542137/c6b9fc84-228f-11e6-9b2e-de748859e693.png)
Rechts oben bei der Kategorie CFD kannst du die Parameter eintragen.

Wenn du den Indikator Info einblendest müsstest du eigentlich alle wichtigen Daten angezeigt bekommen.

**Comment by ckovar82** [comment]
habs gerade für amazon (AMZN.US-XTB.CFD) und adidas (ADS.DE-XTB.CFD) jeweils einen indikatortest gemacht. hat jeweils funktioniert
![image](https://cloud.githubusercontent.com/assets/18376618/15545440/997d987c-229c-11e6-884d-cd271fe59c44.png)

![image](https://cloud.githubusercontent.com/assets/18376618/15545468/acfd3bbe-229c-11e6-8b31-5389550eb964.png)

er macht eigentlich alles richtig für beide märtke. denke mal, dass es an was anderem liegt =(

**Comment by ckovar82** [comment]
hallo dieter,

nach neuerster erkenntnis laufen unsere scripts nicht mehr unter version 1.9. wird ein wenig dauern bis wir die auf die neue systemstruktur hochgezogen haben =(

**Comment by David-Jones1982** [comment]
Guten Tag,

funktionieren eure Conditions, Indikatoren und Strategien zur zeit nur in der neuen Agena Version 1.9?

wollte die mal ausprobieren. Die ORB zeigt bei den Forex Werten nur die Range von 0 bis 1 und bei den Indizes funktioniert sie leider gar nicht.

Daten anbieter ist FXCM (CFD's) vielleicht kann es auch damit was zu tun haben.

Ich hatte schon mal eine Version von euch herruntergeladen die funktioniert hatte.

MFG David

**Comment by simonpucher** [comment]
Hallo David, 
die Scripts funktionieren auf der aktuellen 1.8 und auf der kommenden 1.9 Version. Das ORB Script liest die Daten aus dem Marktplatz-Escort aus. Welche Daten hast du für Forex dort hinterlegt?
![marktplatz](https://cloud.githubusercontent.com/assets/3034492/16679278/968b0da4-44e6-11e6-80ea-fcb03d800871.png)

**Comment by simonpucher** [comment]
Bei CFD verhält es sich genau so. Bei CFD ist am Handelsplatz seitens AT Installation der Wert von 00:00 hinterlegt daher haben wir die Werte für US und DE in das Script codiert.

**Comment by David-Jones1982** [comment]
Hallo Simon danke für deine schnelle hilfe ihr seit wirklich Gold wert.

**Comment by simonpucher** [comment]
Falls es Sinn macht bei den CFD noch andere statische Werte zu hinterlegen, mach einfach ein issue auf und wir schauen uns das an.
Gut wenn es nun für dich geklappt hat! 
Wir sind bei den Beschreibungen ja noch etwas säumig aber wir arbeiten daran.^^
