### ISSUE TITLE
Open Browser Helper

### ISSUE THREAD

**Issue by simonpucher** [simonpucher/AgenaTrader#34]
We need an helper which is able to open browser and display morningstar, google or other finance services.

**Comment by dietsch66** [comment]
?

 

Was ist das?

 

 

Von: Simon Pucher [mailto:notifications@github.com] 
Gesendet: Samstag, 12. November 2016 13:15
An: simonpucher/AgenaTrader
Betreff: [simonpucher/AgenaTrader] Open Browser Helper (#34)

 

We need an helper which is able to open browser and display morningstar, google or other finance services.

**Comment by simonpucher** [comment]
Ich mach sehr viel fundamental daher suche ich eine Möglichkeit um mir diese Fundamentaldaten schnell anzeigbar zu machen.
