### ISSUE TITLE
KingPinball safety extension

### ISSUE THREAD

**Issue by Bytekiller73** [simonpucher/AgenaTrader#51]
Hi Simon,

für das King Pinball System gibt es eine Anpassung zur Absicherung via ATR, leider bin ich noch nicht so weit solch eine Anpassung vor zunehmen. Solltest du Zeit für die Anpassung finden wäre was natürlich bombastisch :), die Erweiterung wird hier detailiert erörtert  https://www.youtube.com/watch?v=blVKBrPsK64

VG, Gregor

**Comment by simonpucher** [comment]
Servus @Bytekiller73, 

die ATR wird als Stop verwendet?
Unser KingPinball Indikator ist nicht für Stops gedacht sondern für den Entry. Die Pfeile Signalisieren LONG und SHORT Richtung.
