### ISSUE TITLE
Multiple Target Order Issue

### ISSUE THREAD

**Issue by Aadhuniksharma** [simonpucher/AgenaTrader#54]
Hi there,
I am trying to code multiple profit target for my entry signal.
`IOrder _orderentershort = SubmitOrder(new StrategyOrderParameters { Direction=OrderDirection.Sell, Type=OrderType.Limit, Price=price ,Quantity=lots, SignalName=uniqueOrderName, FromEntrySignal=_entryOrder.Name });`

The issue is, it is not considering entry order name and the targets remain open even after the entry order closes.

There is another method `SetUpProfitTarget` but we can't set multiple targets there.

**Comment by simonpucher** [comment]
Hi Aadhunik, due the official AgenaTrader documenation the correct method is SetUpProfitTarget
https://agenatrader.github.io/AgenaScript-documentation/strategy_programming/#example_21
If there is a problem with the API then you need to contact AgenaTrader support https://agenatrader.com/de/impressum/
Please tell them which version you are using and send them a test script.
